### ISSUE TITLE
几个问题希望解答

### ISSUE THREAD

**Issue by badboycxcc** [seventeenman/noELF#2]
1. 远程加载后文件会保存的本地吗？如果是这样能不能做到文件不落地直接存放内存加载。
2. 加载执行后会出现被执行程序的进程吗？（加载ls 后会出现一个ls进程吗？）

**Comment by seventeenman** [comment]
1. 不会
2. 注释写了
你有很多cve，应该不是那种不喜欢尝试再问的人
